Do not use bare 'except'.
flake8 rule E722

Exception: as catchall, if
* the right thing to do does not depend on the error
* any error is reported or risen again.

Subversion-Revision: r9033